"""Bake CMU mocap clips into lock/poses.js for the disc wars lock screen.

The clips come from the CMU Graphics Lab Motion Capture Database
(mocap.cs.cmu.edu). Download these into one folder, then run this from it:

    79.asf  79_92.amc       frisbee throw   mocap.cs.cmu.edu/subjects/79/
    124.asf 124_09.amc      stance          mocap.cs.cmu.edu/subjects/124/
    15.asf  15_01.amc       sidestep        mocap.cs.cmu.edu/subjects/15/

    python3 /path/to/tools/bake-poses.py        # writes poses.js here

Each clip: joint positions in metres, 30 fps, the figure turned to face +x
(for the throw: the direction the hand travels at release), standing on y=0,
starting over the origin. Only the joints the scene draws are kept.
"""
import json, math, sys
sys.path.insert(0, __import__("os").path.dirname(__import__("os").path.abspath(__file__)))
from amc import read_asf, read_amc, pose

SCALE = (1.0 / 0.45) * 2.54 / 100.0          # CMU asf/amc units to metres (their FAQ)
JOINTS = ["root", "lhipjoint", "lfemur", "ltibia", "lfoot", "rhipjoint", "rfemur", "rtibia", "rfoot",
          "thorax", "lowerneck", "head", "lclavicle", "lhumerus", "lradius", "lhand",
          "rclavicle", "rhumerus", "rradius", "rhand"]
# Bone ends: femur end = knee, tibia end = ankle, humerus end = elbow, and so on.

def clip(asf, amc, fps, t0, t1, face="hips", out_fps=30):
    bones, parent = read_asf(asf)
    frames = read_amc(amc)
    idx = [int(round(t0 * fps + k * fps / out_fps)) for k in range(int((t1 - t0) * out_fps))]
    P = [pose(bones, parent, frames[i]) for i in idx]
    pts = [[[c * SCALE for c in p[j]] for j in JOINTS] for p in P]
    J = {n: i for i, n in enumerate(JOINTS)}
    # Facing: for the throw, the right hand's horizontal travel at its fastest
    # frame (the release); otherwise perpendicular to the hips.
    release = None
    if face == "throw":
        best = 0
        for k in range(1, len(pts)):
            a, b = pts[k - 1][J["rhand"]], pts[k][J["rhand"]]
            v = math.dist(a, b)
            if v > best: best, release = v, k
        a, b = pts[release - 2][J["rhand"]], pts[release][J["rhand"]]
        fx, fz = b[0] - a[0], b[2] - a[2]
    else:
        l, r = pts[0][J["lfemur"]], pts[0][J["rfemur"]]     # knees; hips are too close together
        hx, hz = r[0] - l[0], r[2] - l[2]
        fx, fz = hz, -hx                                   # forward: perpendicular to left->right, toes ahead
    ang = math.atan2(fz, fx)
    c, s = math.cos(-ang), math.sin(-ang)
    ox, oz = pts[0][J["root"]][0], pts[0][J["root"]][2]
    floor = min(p[J[f]][1] for p in pts for f in ("lfoot", "rfoot"))
    out = []
    for p in pts:
        fr = []
        for x, y, z in p:
            x, z = x - ox, z - oz
            fr += [round(x * c - z * s, 3), round(y - floor, 3), round(x * s + z * c, 3)]
        out.append(fr)
    return {"frames": out, "release": release}

clips = {
    "throw": clip("79.asf", "79_92.amc", 60, 2.2, 3.5, face="throw"),
    "idle": clip("124.asf", "124_09.amc", 120, 12.4, 14.0),
    "dodge": clip("15.asf", "15_01.amc", 120, 16.9, 18.3),
}
# Sanity: after turning, the toes should point ahead (+x) of the ankles.
for name, cl in clips.items():
    f = cl["frames"][0]; J = {n: i for i, n in enumerate(JOINTS)}
    toes = [f[3*J[s + "foot"]] - f[3*J[s + "tibia"]] for s in "lr"]
    print(name, len(cl["frames"]), "frames, release", cl["release"],
          "toe dx %.2f %.2f" % tuple(toes), "height %.2f m" % max(f[1::3]))
    assert min(toes) > 0, name + " faces backwards"
js = ["// Baked from the CMU Graphics Lab Motion Capture Database (mocap.cs.cmu.edu):",
      "// 79_92 (frisbee throw), 124_09 (stance), 15_01 (sidestep). Generated by tools/bake-poses.py.",
      ".pragma library",
      "var fps = 30;",
      "var joints = " + json.dumps(JOINTS) + ";",
      "var clips = " + json.dumps(clips, separators=(",", ":")) + ";"]
open("poses.js", "w").write("\n".join(js) + "\n")
import os; print("poses.js", os.path.getsize("poses.js"), "bytes")
